[tool.poetry]
name = "poetry-issue-repro"
version = "0.1.0"
description = ""
authors = ["Matthew Elwell <matthew.elwell@flagsmith.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
